version: '3'

services:
  app:
    build:
      context: .
    container_name: doc_chat
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"    
    environment:
      DJANGO_ENV: development
